/*
 Copyright (C) 2011 Red Soldier Limited. All rights reserved.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#import <Foundation/Foundation.h>
#import "JSON.h"    
#import "RowBasedPageTemplate.h"
#import "ColumnBasedPageTemplate.h"
#import "StoriesFeed.h"
#import "ImageTitleText.h"
#import "StoriesPageView.h"
#import "Story.h"

#define CONTENT_AREA_HEADER 100.0f
#define CONTENT_AREA_MARGIN_TOP 20.0f
#define CONTENT_AREA_MARGIN_SIDE 10.0f
#define CONTENT_AREA_MARGIN_BOTTOM 20.0f

#define SECTION_TITLE_IMAGE_ABSTRACT @"TIA"
#define SECTION_IMAGE_TITLE_ABSTRACT @"ITA"
#define SECTION_TITLE_ABSTRACT_IMAGE_RIGHT @"TAIR"
#define SECTION_TITLE_ABSTRACT_IMAGE_LEFT @"TAIL"

@interface PageLayoutManager : NSObject {
    
}

- (NSMutableArray*) parsePageTemplateConfig:(NSString*)templateConfig;
- (NSMutableArray*) constructPagesWithTemplate:(NSMutableArray*)pageTemplatesArray storiesFeed:(StoriesFeed*)storiesFeed;

@end
